# Generated by Django 4.0.3 on 2022-03-29 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='avatars')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('latitude', models.FloatField(blank=True, default=None, max_length=30)),
                ('longitude', models.FloatField(blank=True, default=None, max_length=30)),
                ('sympathy', models.ManyToManyField(blank=True, to='members.person')),
            ],
        ),
    ]
