# Generated by Django 4.0.3 on 2022-03-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='latitude',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='longitude',
            field=models.FloatField(max_length=30),
        ),
    ]
