# Generated by Django 4.0.3 on 2022-03-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
